### ISSUE TITLE
Crash when killing a Nitwit (green robe) villager using IC2 dynamite

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Pillagers#2]
AFAIK this only works with the dynamite.

---- Minecraft Crash Report ----
// You're mean.

Time: 2019-06-07 14:26:09 EDT
Description: Ticking entity

java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Random.java:388)
    at net.darkhax.pillagers.Pillagers.onMobKilled(Pillagers.java:57)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1314_Pillagers_onMobKilled_LivingDropsEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:619)
    at net.minecraft.entity.EntityLivingBase.onDeath(EntityLivingBase.java:1202)
    at net.minecraft.entity.passive.EntityVillager.onDeath(EntityVillager.java:536)
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1023)
    at ic2.core.PointExplosion.doExplosionA(PointExplosion.java:72)
    at ic2.core.block.EntityDynamite.explode(EntityDynamite.java:215)
    at ic2.core.block.EntityDynamite.onUpdate(EntityDynamite.java:122)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zbj000(World.java:4118)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: ic2:sticky_dynamite (ic2.core.block.EntityStickyDynamite)
  Entity ID: 3141
  Entity Name: entity.StickyDynamite.name
  Entity's Exact location: -980.12, 6.79, -431.99
  Entity's Block location: World: (-981,6,-432), Chunk: (at 11,0,0 in -62,-27; contains blocks -992,0,-432 to -977,255,-417), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
  Entity's Momentum: 0.00, 0.00, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {Motion:[0.0d,0.0d,0.0d],ForgeData:{},UUIDLeast:-5852441689340213055L,inGround:1b,Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,Rotation:[-106.01334f,-21.872278f],UpdateBlocked:0b,FallDistance:0.0f,UUIDMost:9147673142939961123L,Pos:[-980.124720550391d,6.789338214776949d,-431.99315223210857d],Fire:-1s,SurgeAABB:[-980.374720550391d,6.789338214776949d,-432.24315223210857d,-979.874720550391d,7.289338214776949d,-431.74315223210857d]}

-- Affected level --
  Level name: test
  All players: 1 total; [GCEntityPlayerMP['cowboycosmic'/1770, l='test', x=-973.28, y=4.00, z=-432.92]]
  Chunk stats: ServerChunkCache: 413 Drop: 0
  Level seed: -6723921365859320795
  Level generator: ID 01 - flat, ver 0. Features enabled: true
  Level generator options: 
  Level spawn location: World: (-169,4,438), Chunk: (at 7,0,6 in -11,27; contains blocks -176,0,432 to -161,255,447), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 50671 game time, 50671 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 55136 (now: false), thunder time: 8630 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 710575008 bytes (677 MB) / 2803892224 bytes (2674 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 168 mods loaded, 168 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                     | Version                     | Source                                                                | Signature                                |
       |:------ |:---------------------- |:--------------------------- |:--------------------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft              | 1.12.2                      | minecraft.jar                                                         | None                                     |
       | LCHIJA | mcp                    | 9.42                        | minecraft.jar                                                         | None                                     |
       | LCHIJA | FML                    | 8.0.99.99                   | forge-1.12.2-14.23.5.2838.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                  | 14.23.5.2838                | forge-1.12.2-14.23.5.2838.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy      | 1.0.0                       | minecraft.jar                                                         | None                                     |
       | LCHIJA | micdoodlecore          |                             | minecraft.jar                                                         | None                                     |
       | LCHIJA | foamfixcore            | 7.7.4                       | minecraft.jar                                                         | None                                     |
       | LCHIJA | obfuscate              | 0.2.6                       | minecraft.jar                                                         | None                                     |
       | LCHIJA | opencomputers|core     | 1.7.4.153                   | minecraft.jar                                                         | None                                     |
       | LCHIJA | botania_tweaks_core    | -100                        | minecraft.jar                                                         | None                                     |
       | LCHIJA | additionalbanners      | 1.1.76                      | AdditionalBanners-1.12.2-1.1.76.jar                                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | aether_legacy          | 1.4.4                       | aether_legacy-1.12.2-v1.4.4.jar                                       | None                                     |
       | LCHIJA | aiimprovements         | 0.0.1.3                     | AIImprovements-1.12-0.0.1b3.jar                                       | None                                     |
       | LCHIJA | applecore              | 3.2.0                       | AppleCore-mc1.12.2-3.2.0.jar                                          | None                                     |
       | LCHIJA | charset                | 0.5.5.7                     | Charset-Lib-0.5.5.7.jar                                               | None                                     |
       | LCHIJA | crafttweaker           | 4.1.18                      | CraftTweaker2-1.12-4.1.18.jar                                         | None                                     |
       | LCHIJA | mtlib                  | 3.0.6                       | MTLib-3.0.6.jar                                                       | None                                     |
       | LCHIJA | modtweaker             | 4.0.17                      | modtweaker-4.0.17.jar                                                 | None                                     |
       | LCHIJA | jei                    | 4.15.0.268                  | jei_1.12.2-4.15.0.268.jar                                             | None                                     |
       | LCHIJA | appleskin              | 1.0.9                       | AppleSkin-mc1.12-1.0.9.jar                                            | None                                     |
       | LCHIJA | morphtool              | 1.2-21                      | Morph-o-Tool-1.2-21.jar                                               | None                                     |
       | LCHIJA | quark                  | r1.5-156                    | Quark-r1.5-156.jar                                                    | None                                     |
       | LCHIJA | autoreglib             | 1.3-30                      | AutoRegLib-1.3-30.jar                                                 | None                                     |
       | LCHIJA | baubles                | 1.5.2                       | Baubles-1.12-1.5.2.jar                                                | None                                     |
       | LCHIJA | baubleofundying        | 1.0.1                       | BaubleOfUndying-1.12-1.0.1.jar                                        | None                                     |
       | LCHIJA | baubleshud             | 5.0.2                       | BaublesHud-1.12.2-5.0.2.jar                                           | None                                     |
       | LCHIJA | bibliocraft            | 2.4.5                       | BiblioCraft[v2.4.5][MC1.12.2].jar                                     | None                                     |
       | LCHIJA | mts                    | 14.3.0                      | Immersive Vehicles-1.12.2-14.3.0.jar                                  | None                                     |
       | LCHIJA | unuparts               | 1.11.2                      | UNU Parts Pack [MTS] 1.10.2-14.0.0-1.11.2.jar                         | None                                     |
       | LCHIJA | blackthorne            | 1.11.2                      | BlackThorne Empire Vehicles [MTS] [IR] 1.10.2-14.0.0-1.5.0-1.11.2.jar | None                                     |
       | LCHIJA | bloodmoon              | 1.5.3                       | Bloodmoon-MC1.12.2-1.5.3.jar                                          | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | bonsaitrees            | 1.1.3                       | bonsaitrees-1.1.3-b156.jar                                            | None                                     |
       | LCHIJA | bookshelf              | 2.3.581                     | Bookshelf-1.12.2-2.3.581.jar                                          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | botania_tweaks         | 1.8.5                       | botaniatweaks-1.8.5.jar                                               | None                                     |
       | LCHIJA | thaumcraft             | 6.1.BETA26                  | Thaumcraft-1.12.2-6.1.BETA26.jar                                      | None                                     |
       | LCHIJA | botania                | r1.10-361                   | Botania r1.10-361.jar                                                 | None                                     |
       | LCHIJA | cctweaked              | 1.83.1                      | cc-tweaked-1.12.2-1.83.1.jar                                          | None                                     |
       | LCHIJA | computercraft          | 1.83.1                      | cc-tweaked-1.12.2-1.83.1.jar                                          | None                                     |
       | LCHIJA | codechickenlib         | 3.2.2.353                   | CodeChickenLib-1.12.2-3.2.2.353-universal.jar                         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | chickenchunks          | 2.4.1.73                    | ChickenChunks-1.12.2-2.4.1.73-universal.jar                           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | classicbar             | @VERSION@                   | classicbar-0.3.2c.jar                                                 | None                                     |
       | LCHIJA | classiccombat          | 1.0.1                       | ClassicCombat-1.0.1.jar                                               | None                                     |
       | LCHIJA | ichunutil              | 7.2.1                       | iChunUtil-1.12.2-7.2.1.jar                                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | clef                   | 7.1.0                       | Clef-1.12.2-7.1.0.jar                                                 | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | clienttweaks           | 3.1.11                      | ClientTweaks_1.12.2-3.1.11.jar                                        | None                                     |
       | LCHIJA | clumps                 | 3.1.2                       | Clumps-3.1.2.jar                                                      | None                                     |
       | LCHIJA | redstoneflux           | 2.1.0                       | RedstoneFlux-1.12-2.1.0.6-universal.jar                               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cofhcore               | 4.6.3                       | CoFHCore-1.12.2-4.6.3.27-universal.jar                                | None                                     |
       | LCHIJA | cofhworld              | 1.3.1                       | CoFHWorld-1.12.2-1.3.1.7-universal.jar                                | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | toughasnails           | 3.1.0.139                   | ToughAsNails-1.12.2-3.1.0.139-universal.jar                           | None                                     |
       | LCHIJA | comforts               | 1.4.1.2                     | comforts-1.12.2-1.4.1.2.jar                                           | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | ctgui                  | 1.0.0                       | CraftTweaker2-1.12-4.1.18.jar                                         | None                                     |
       | LCHIJA | crafttweakerjei        | 2.0.3                       | CraftTweaker2-1.12-4.1.18.jar                                         | None                                     |
       | LCHIJA | creativecore           | 1.9.9                       | CreativeCore_v1.9.45_mc1.12.2.jar                                     | None                                     |
       | LCHIJA | ctm                    | MC1.12.2-0.3.3.22           | CTM-MC1.12.2-0.3.3.22.jar                                             | None                                     |
       | LCHIJA | cucumber               | 1.1.3                       | Cucumber-1.12.2-1.1.3.jar                                             | None                                     |
       | LCHIJA | custombackgrounds      | 1.0                         | CustomBackgrounds-MC1.12-1.1.1.jar                                    | None                                     |
       | LCHIJA | custommainmenu         | 2.0.9                       | CustomMainMenu-MC1.12.2-2.0.9.jar                                     | None                                     |
       | LCHIJA | waila                  | 1.8.26                      | Hwyla-1.8.26-B41_1.12.2.jar                                           | None                                     |
       | LCHIJA | darkutils              | 1.8.226                     | DarkUtils-1.12.2-1.8.226.jar                                          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | dimdoors               | 3.0.9+287                   | DimensionalDoors-3.0.9-287.jar                                        | None                                     |
       | LCHIJA | dwtmtspack             | 8.0.0                       | DWTPack_V0.8.jar                                                      | None                                     |
       | LCHIJA | thermalfoundation      | 2.6.3                       | ThermalFoundation-1.12.2-2.6.3.27-universal.jar                       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | immersiveengineering   | 0.12-89                     | ImmersiveEngineering-0.12-89.jar                                      | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCHIJA | engineersdoors         | 0.8.0                       | engineers_doors-1.12.2-0.8.0.jar                                      | None                                     |
       | LCHIJA | expandedbonemeal       | 1.2.1                       | expandedbonemeal-1.11-1.2.1.jar                                       | None                                     |
       | LCHIJA | fastfurnace            | 1.3.1                       | FastFurnace-1.12.2-1.3.1.jar                                          | None                                     |
       | LCHIJA | fastbench              | 1.7.2                       | FastWorkbench-1.12.2-1.7.2.jar                                        | None                                     |
       | LCHIJA | fencejumper            | 1.0.5                       | fencejumper-1.12-1.0.5.jar                                            | None                                     |
       | LCHIJA | fenceoverhaul          | 1.3.4                       | FenceOverhaul-1.3.4.jar                                               | None                                     |
       | LCHIJA | findme                 | 1.1.0                       | findme-1.12.2-1.1.0-8.jar                                             | None                                     |
       | LCHIJA | foamfix                | 0.10.5-1.12.2               | foamfix-0.10.5-1.12.2.jar                                             | None                                     |
       | LCHIJA | forgemultipartcbe      | 2.6.1.81                    | ForgeMultipart-1.12.2-2.6.1.81-universal.jar                          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | microblockcbe          | 2.6.1.81                    | ForgeMultipart-1.12.2-2.6.1.81-universal.jar                          | None                                     |
       | LCHIJA | minecraftmultipartcbe  | 2.6.1.81                    | ForgeMultipart-1.12.2-2.6.1.81-universal.jar                          | None                                     |
       | LCHIJA | forgivingvoid          | 1.0.22                      | ForgivingVoid_1.12.2-1.0.22.jar                                       | None                                     |
       | LCHIJA | ftblib                 | 5.4.3.103                   | FTBLib-5.4.3.103.jar                                                  | None                                     |
       | LCHIJA | ftbutilities           | 5.4.0.97                    | FTBUtilities-5.4.0.97.jar                                             | None                                     |
       | LCHIJA | ftbbackups             | 0.0.0.ftbbackups            | FTBUtilitiesBackups-1.0.0.4.jar                                       | None                                     |
       | LCHIJA | cfm                    | 6.3.0                       | furniture-6.3.0-1.12.2.jar                                            | None                                     |
       | LCHIJA | minecraftfuture        | 0.1.5                       | future-mc-0.1.5c.jar                                                  | None                                     |
       | LCHIJA | ic2                    | 2.8.109-ex112               | industrialcraft-2-2.8.109-ex112.jar                                   | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | mantle                 | 1.12-1.3.3.55               | Mantle-1.12-1.3.3.55.jar                                              | None                                     |
       | LCHIJA | galacticraftcore       | 4.0.2.210                   | GalacticraftCore-1.12.2-4.0.2.210.jar                                 | None                                     |
       | LCHIJA | galacticraftplanets    | 4.0.2.210                   | Galacticraft-Planets-1.12.2-4.0.2.210.jar                             | None                                     |
       | LCHIJA | galacticrafttweaker    | 1.12.2-1.0.3                | GalacticraftTweaker-1.12.2-1.0.3.jar                                  | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | globalgamerules        | 2.2                         | GlobalGameRules-1.12.2-2.2.7.jar                                      | None                                     |
       | LCHIJA | guideapi               | 1.12-2.1.8-63               | Guide-API-1.12-2.1.8-63.jar                                           | None                                     |
       | LCHIJA | tardis                 | 0.1.0D                      | tardis-0.1.0D.jar                                                     | None                                     |
       | LCHIJA | handles                | 1.12.2-1.5.1.4              | handles-1.12.2-1.5.1.4.jar                                            | None                                     |
       | LCHIJA | headcrumbs             | 2.0.4                       | Headcrumbs-1.12.2-2.0.5.17.jar                                        | None                                     |
       | LCHIJA | hopperducts            | 1.5                         | hopperducts-mc1.12-1.5.jar                                            | None                                     |
       | LCHIJA | ic2magma               | 1.0 - MC 1.12.2             | ic2magma-1.0.jar                                                      | None                                     |
       | LCHIJA | mtsseagullcivilpack    | 2.0.0                       | Immersive Vehicles (IV) Seagull's civil pack 1.20.0.jar               | None                                     |
       | LCHIJA | mtsseagullmilitarypack | 1.4.0                       | Immersive Vehicles (IV) Seagull's military pack 1.7.3.jar             | None                                     |
       | LCHIJA | mtsseagulltrinpartpack | 1.0.0                       | Immersive Vehicles (IV) Seagull's trin parts pack 1.11.1.jar          | None                                     |
       | LCHIJA | initialinventory       | 2.0.2                       | InitialInventory-3.0.0.jar                                            | None                                     |
       | LCHIJA | inspirations           | 1.12.2-0.2.4                | Inspirations-1.12.2-0.2.4.jar                                         | None                                     |
       | LCHIJA | inventoryspam          | 1.0.5                       | InventorySpam-1.12.2-1.0.5.jar                                        | None                                     |
       | LCHIJA | inventorytweaks        | 1.63+release.109.220f184    | InventoryTweaks-1.63.jar                                              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironbackpacks          | 1.12.2-3.0.8-12             | IronBackpacks-1.12.2-3.0.8-12.jar                                     | None                                     |
       | LCHIJA | ironchest              | 1.12.2-7.0.67.844           | ironchest-1.12.2-7.0.67.844.jar                                       | None                                     |
       | LCHIJA | ironjetpacks           | 1.1.0                       | IronJetpacks-1.12-2-1.1.0.jar                                         | None                                     |
       | LCHIJA | itlt                   | 1.0.0                       | itlt-1.12-1.0.0.jar                                                   | None                                     |
       | LCHIJA | joshxmas               | 1.12.2-1.2.0                | joshxmas-1.12.2-1.2.0.jar                                             | None                                     |
       | LCHIJA | journeymap             | 1.12.2-5.5.4                | journeymap-1.12.2-5.5.4.jar                                           | None                                     |
       | LCHIJA | keywizard              | 1.12.2-1.6                  | keywizard-1.12.2-1.6.jar                                              | None                                     |
       | LCHIJA | lex                    | 1.0.8                       | LibEx-1.12.2-1.0.8.jar                                                | None                                     |
       | LCHIJA | livingenchantment      | 3.1.9                       | living_enchantment-3.1.9.jar                                          | None                                     |
       | LCHIJA | locks                  | 2.2.1                       | Locks-2.2.1.jar                                                       | None                                     |
       | LCHIJA | lost_aether            | 0.0.3                       | lost_aether-content-1.12.2-v0.0.3.jar                                 | None                                     |
       | LCHIJA | lostcities             | 2.0.20                      | lostcities-1.12-2.0.20.jar                                            | None                                     |
       | LCHIJA | mcjtylib_ng            | 3.5.3                       | mcjtylib-1.12-3.5.3.jar                                               | None                                     |
       | LCHIJA | mcmultipart            | 2.5.3                       | MCMultiPart-2.5.3.jar                                                 | None                                     |
       | LCHIJA | melvinssignpack        | 1.0.0                       | Melvins_Simple_Sign_Pack-Beta-0.0.5.jar                               | None                                     |
       | LCHIJA | mendingfix             | 1.0.1-1.12.2.2618           | mendingfix-1.0.1-1.12.2.2618.jar                                      | None                                     |
       | LCHIJA | mtrm                   | 1.2.2.30                    | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar                            | None                                     |
       | LCHIJA | mjrlegendslib          | 1.12.2-1.1.8                | MJRLegendsLib-1.12.2-1.1.8.jar                                        | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | testdummy              | 1.12                        | MmmMmmMmmMmm-1.12-1.14.jar                                            | None                                     |
       | LCHIJA | morecauldrons          | 1.4.4                       | More-Cauldrons-1.4.4.jar                                              | None                                     |
       | LCHIJA | mtsofficialpack        | 11.0.0                      | MTS_Official_Pack_V11.jar                                             | None                                     |
       | LCHIJA | mundaneredstone        | 1.1.4                       | MundaneRedstone-1.1.4.jar                                             | None                                     |
       | LCHIJA | netherportalfix        | 5.3.17                      | NetherPortalFix_1.12.1-5.3.17.jar                                     | None                                     |
       | LCHIJA | nodami                 | 1.2.1                       | nodami-1.12.2-1.2.1.jar                                               | None                                     |
       | LCHIJA | nonvflash              | 1.2.0                       | NoNVFlash-1.12.2-1.2.0.3-universal.jar                                | None                                     |
       | LCHIJA | norecipebook           | 1.2.1                       | noRecipeBook_v1.2.2formc1.12.2.jar                                    | None                                     |
       | LCHIJA | opencomputers          | 1.7.4.153                   | OpenComputers-MC1.12.2-1.7.4.153.jar                                  | None                                     |
       | LCHIJA | p455w0rdslib           | 2.1.44                      | p455w0rdslib-1.12.2-2.1.44.jar                                        | None                                     |
       | LCHIJA | prestige               | 1.1.51                      | Prestige-1.12.2-1.1.51.jar                                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | parabox                | 1.1.4                       | Parabox-1.12.2-1.1.4.jar                                              | None                                     |
       | LCHIJA | pillagers              | 1.0.2                       | Pillagers-1.12.2-1.0.2.jar                                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | playerrevive           | 1.0                         | PlayerRevive_v1.2.26_mc1.12.2.jar                                     | None                                     |
       | LCHIJA | playersdropheads       | 1.1.0                       | playersdropheads-1.12.x-1.1.0.jar                                     | None                                     |
       | LCHIJA | prettybeaches          | 1.0.4                       | PrettyBeaches_1.12.2-1.0.4.jar                                        | None                                     |
       | LCHIJA | quickleafdecay         | 1.2.4                       | QuickLeafDecay-MC1.12.1-1.2.4.jar                                     | None                                     |
       | LCHIJA | randomthings           | 4.2.7.1                     | RandomThings-MC1.12.2-4.2.7.1.jar                                     | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | realdrops              | 1.2.14                      | RealisticItemDrops-1.2.14.jar                                         | None                                     |
       | LCHIJA | refinedstorage         | 1.6.14                      | refinedstorage-1.6.14.jar                                             | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LCHIJA | refinedstorageaddons   | 0.4.4                       | refinedstorageaddons-0.4.4.jar                                        | None                                     |
       | LCHIJA | regeneration           | 1.6.4                       | Regeneration-1.12.2-1.6.4.jar                                         | None                                     |
       | LCHIJA | resound                | 1r                          | ReSound-1.12.2-1r.jar                                                 | None                                     |
       | LCHIJA | respawntimer           | $version                    | respawntimer-1.12.2-2.0.0.0.jar                                       | None                                     |
       | LCHIJA | roguelike              | 1.8.0                       | RoguelikeDungeons-1.12.2-1.8.0.jar                                    | None                                     |
       | LCHIJA | roost                  | 2.0.10                      | roost-1.12.2-2.0.10.jar                                               | None                                     |
       | LCHIJA | sanlib                 | 1.5.1                       | SanLib-1.12.2-1.5.1.jar                                               | df48348748b5e141b1d118e2302a8d5be930b708 |
       | LCHIJA | sanplayermodel         | 1.1.1                       | SanLib-1.12.2-1.5.1.jar                                               | None                                     |
       | LCHIJA | sbmpuntanimal          | 1.12.2-1.0.0.20190202141056 | SBM-Punt-Animal-1.12.2-1.0.0b20190202141059.jar                       | None                                     |
       | LCHIJA | seedcopy               | 3.0.6                       | SeedCopy-1.9-3.0.6.jar                                                | None                                     |
       | LCHIJA | spiceoflife            | 1.3.12                      | SpiceOfLife-mc1.12-1.3.12.jar                                         | None                                     |
       | LCHIJA | surge                  | 2.0.77                      | Surge-1.12.2-2.0.77.jar                                               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | sync                   | 7.1.0                       | Sync-1.12.2-7.1.0.jar                                                 | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | thaumicjei             | 1.6.0                       | ThaumicJEI-1.12.2-1.6.0-27.jar                                        | None                                     |
       | LCHIJA | thaumicperiphery       | 0.3.0                       | thaumicperiphery-0.3.0.jar                                            | None                                     |
       | LCHIJA | thermalexpansion       | 5.5.4                       | ThermalExpansion-1.12.2-5.5.4.43-universal.jar                        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermaldynamics        | 2.5.5                       | ThermalDynamics-1.12.2-2.5.5.21-universal.jar                         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalinnovation      | 0.3.3                       | ThermalInnovation-1.12.2-0.3.3.12-universal.jar                       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | t3gssksignspack        | 1.0.1                       | Tim3Game's European Signs Pack 1.0.1.jar                              | None                                     |
       | LCHIJA | tips                   | 1.0.7                       | Tips-1.12.2-1.0.7.jar                                                 | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | tumbleweed             | 1.11-0.4.5                  | tumbleweed-1.11-0.4.5.jar                                             | None                                     |
       | LCHIJA | vanillafix             | 1.0.10-SNAPSHOT             | VanillaFix-1.0.10-99.jar                                              | None                                     |
       | LCHIJA | vanillatools           | 1.1.0                       | VanillaTools-1.12.2-1.1.0.2-universal.jar                             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | walljump               | 1.12.2-1.2.3                | walljump-1.12.2-1.2.3.jar                                             | None                                     |
       | LCHIJA | wanionlib              | 1.12.2-2.2                  | WanionLib-1.12.2-2.2.jar                                              | None                                     |
       | LCHIJA | wawla                  | 2.5.273                     | Wawla-1.12.2-2.5.273.jar                                              | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | k9                     | 1.12.2-1.3.1.2              | k9-1.12.2-1.3.1.2.jar                                                 | None                                     |
       | LCHIJA | vt                     | 1.4.8                       | VanillaTweaks-1.4.8.jar                                               | None                                     |
       | LCHIJA | weeping-angels         | 1.12.2-37                   | weeping-angels-37.jar                                                 | None                                     |
       | LCHIJA | unidict                | 1.12.2-2.9.2                | UniDict-1.12.2-2.9.2.jar                                              | None                                     |
  Loaded coremods (and transformers): LoadingPlugin (RandomThings-MC1.12.2-4.2.7.1.jar)
                                        lumien.randomthings.asm.ClassTransformer
                                      SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
                                        pl.asie.splashanimation.core.SplashProgressTransformer
                                      RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
                                        pw.prok.realbench.asm.RBTransformer
                                      BedPatch (bedpatch-2.2-1.12.2.jar)
                                        com.mordenkainen.bedpatch.BedPatchASM
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      CreativePatchingLoader (CreativeCore_v1.9.45_mc1.12.2.jar)
                                        
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      Regeneration Sound Handler (Regeneration-1.12.2-1.6.4.jar)
                                        me.suff.regeneration.client.sound.echo.RegenClassTransformer
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      F5FixLoadingPlugin (f5fix-1.2.jar)
                                        de.morrien.f5fix.F5FixTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      Quark Plugin (Quark-r1.5-156.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      Botania Tweaks Core (botaniatweaks-1.8.5.jar)
                                        quaternary.botaniatweaks.asm.BotaniaTweakerTransformer
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
                                     - ToughAsNailsPlugin (Enabled/Not Forced)
                                     - WailaPlugin (Enabled/Not Forced)
  Suspected Mods: Pillagers (pillagers), IndustrialCraft 2 (ic2)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [GCEntityPlayerMP['cowboycosmic'/1770, l='test', x=-973.28, y=4.00, z=-432.92]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Client Crashes Since Restart: 0
  Integrated Server Crashes Since Restart: 1

**Comment by Darkhax** [comment]
Thanks for reporting this issue. It should be fixed in the next update.
